// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-2:d0e4a4f8-c52c-49ac-8239-51af34542b0d',
    'aws_cognito_region': 'ap-northeast-2',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '0f15b186624f438987a86e2ca9e642a7',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ec12fcb8-a028-4d07-aa1c-7bff3173ba4a',
    'aws_project_name': 'hckim-react-test',
    'aws_project_region': 'ap-northeast-2',
    'aws_resource_name_prefix': 'hckimreacttest-mobilehub-510907955',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-2_1xL3AFNbe',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '21bihl1nvf1a1kdvi7g6glc0c2',
}

export default awsmobile;
